### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by rinkeChillow** [Roundaround/mc-fabric-experience-progress#4]
i was thinking about a smaller size for the number that will make the user experience much better 
here are some examples:
![image](https://github.com/user-attachments/assets/fbd96b24-1147-4f2e-98b5-828a3aa67902)
sorry for the messy hotbar 😅
i think that would make people use the mod not as a debug feature but as an always on gameplay addition that doesn't get in the way but make the game that bit better
here is a full screen test of my idea:
![image](https://github.com/user-attachments/assets/efb0c074-1397-45ed-88b5-de20e7f87098)
again sorry for the mess.

**Comment by rinkeChillow** [comment]
and sorry for reaching out like this , i didn't find any other way

**Comment by Roundaround** [comment]
At the moment, all the text in the game is one consistent size - there's really no concept of "smaller text". It's technically possible, but not something I'm interested in implementing at this time. Sorry!
